version: "3"

services:
  webserver:
    container_name: webserver
    restart: always
    build:
      context: ../
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8888:80"
      - "443:443"
    volumes:
      - ./../src/:/var/www/html/